[build]
command = """
curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
apt-get install -y nodejs
npm install -g pnpm
cd page && pnpm install && pnpm run build
"""

[start]
command = "cd page && pnpm run preview"
